{% set name = "kornia-rs" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kornia/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 547a01735791de4afcfcd6e01de8a72bca5539c3b88857770edaa9d45b7bd728

build:
  number: 2
  skip: true  # [py>312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
    - cmake
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.3.2
    - pip
    - gstreamer
    - gst-plugins-base {{ gstreamer }}
    - libjpeg-turbo
    - nasm
    - glib
    - gtk3
  run:
    - python

test:
  imports:
    - kornia_rs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kornia/kornia-rs
  summary: Low level implementations for computer vision in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://docs.rs/kornia-rs

extra:
  recipe-maintainers:
    - edgarriba
    - mukhery
