{% set name = "kornia-rs" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kornia_rs-{{ version }}.tar.gz
  sha256: 00520988740e9de1682f2f682caecb9b740d2489f3fbbb1ca0b6fc56af70d298

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.3.2
    - pip
    - gstreamer
    - libjpeg-turbo
    - nasm
  run:
    - python

test:
  imports:
    - kornia_rs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kornia/kornia-rs
  summary: Low level implementations for computer vision in Rust
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  doc_url: https://docs.rs/kornia-rs

extra:
  recipe-maintainers:
    - edgarriba
    - mukhery
